server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: xw-picture-backend
    # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xw_picture?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 5000
  profiles:
    active: local
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 开发环境下打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段名
      logic-not-delete-value: 0 # 逻辑未删除值
      logic-delete-value: 1 # 逻辑删除值

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v4.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xiaowang.xwpicturebackend.controller

#对象存储配置
#cos:
#  client:
#    host:
#    secretId:
#    secretKey:
#    region:
#    bucet: